# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY cmd/audio-processor/go.mod cmd/audio-processor/go.sum ./
RUN go mod download
COPY cmd/audio-processor/ ./
COPY pkg/protogen/ ./pkg/protogen/
RUN go build -o audio-processor main.go

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /app/audio-processor .
EXPOSE 50051
CMD ["/audio-processor"] 