# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY cmd/orchestrator/go.mod cmd/orchestrator/go.sum ./
RUN go mod download
COPY cmd/orchestrator/ ./
COPY pkg/protogen/ ./pkg/protogen/
RUN go build -o orchestrator main.go

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /app/orchestrator .
EXPOSE 50053
CMD ["/orchestrator"] 