# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY cmd/whatsapp-gateway/go.mod cmd/whatsapp-gateway/go.sum ./
RUN go mod download
COPY cmd/whatsapp-gateway/ ./
COPY internal/ ./internal/
COPY pkg/protogen/ ./pkg/protogen/
RUN go build -o whatsapp-gateway main.go

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /app/whatsapp-gateway .
EXPOSE 8080
CMD ["/whatsapp-gateway"] 