# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY cmd/text-summarizer/go.mod cmd/text-summarizer/go.sum ./
RUN go mod download
COPY cmd/text-summarizer/ ./
COPY pkg/protogen/ ./pkg/protogen/
RUN go build -o text-summarizer main.go

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /app/text-summarizer .
EXPOSE 50052
CMD ["/text-summarizer"] 